- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.9.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
      creates: cluster_initialized.txt

    - name: waiting for kube services
      wait_for:
        timeout: 155

    - name: create .kube directory
      #become: yes
      #become_user: centos
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        #owner: centos

    - name: install Pod network
      #      become: yes
      #      become_user: tetrawing
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
    - name: creating IP pool and configuring master node
      wait_for:
        timeout: 15

